from game.shared.color import Color

# GAME
CAPTION = "Pong"
FRAME_RATE = 60
CELL_SIZE = 15

# SCREEN
MAX_X = 1200
MAX_Y = 600
CENTER_X = int(MAX_X / 2)
CENTER_Y = int(MAX_Y / 2)

# FIELD
FIELD_TOP = 1
FIELD_BOTTOM = MAX_Y
FIELD_LEFT = 0
FIELD_RIGHT = MAX_X

# COLOR
BLACK = Color(0, 0, 0)
WHITE = Color(255, 255, 255)
PURPLE = Color(255, 0, 255)

# BALL
BALL_GROUP = "balls"
BALL_WIDTH = 28
BALL_HEIGHT = 28
BALL_VELOCITY = 5

# PADDLE
PADDLE_GROUP = "paddles"
PADDLE_WIDTH = 10
PADDLE_HEIGHT = 75
PADDLE_RATE = 6
PADDLE_VELOCITY = 7